#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# alias
alias f='fastfetch'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias cls='clear'
alias ll='ls -lh --color=auto'

PS1='\[\033[1;32m\][\u@\h \w]\$\[\033[0m\] '

// niri
if [[ ! -v NIRI_RUNNING ]]; then
  export NIRI_RUNNING=1
  niri-session 2>/dev/null
fi
export PATH="$HOME/.local/bin:$PATH"
